version: '3'

services:
  app:
    container_name: app
    build:
      context: .docker/node
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    entrypoint: .docker/node/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000